<?php

$lines = "paul.ahern@locationmattersinc.com
alex@agggroupoc.com
alex@thepatiosd.com
debbie@higginscapital.com
viveca@hollanderdg.com
marc@acrobatoutsourcing.com
ncoulon@foxrc.net
rbeagles@micros.com
jhaeussler@mcmillin.com
mark@recrepublic.com
hgarlichs@vertosmed.com
david@nibblechocolates.com
dwfreed@aol.com
bmiller@eatdrinkandsleep.net
gejink@gmail.com
utcbusiness@apple.com
allan.farwell@hyatt.com
carlos@primecaptialequities.com
inspirewellnessmd@gmail.com
marduino@mcmillin.com
ncadieux@mcmillin.com
eflores@abbotteng.com
rbenson@bensonbohl.com
akgserv@gmail.com
pete@signdistinction.com
joe.lee2@ecolab.com
lisaakendall@gmail.com
lkarimi@westgatehotel.com
jcline@modernluxury.com
tracyneumann@pacbell.net
tarnett@tsaci.com
sony.ben-moshe@lw.com
seanbrosnan13@gmail.com
chow1@cox.net
rbeagle@micros.com
rjchef1@gmail.com
rk@idymg.com
dr.mike1@cox.net
ambrosefraser@sbcglobal.net
mom@kellycapital.com
kristen@mjemarketing.com
jmarmon@gmail.com
johnnym10@aol.com
dayna@powerstripstudio.com
craigb@calstrat.com
tk1118311@yahoo.com
rbranch@pacificenterprisebank.com
perlmanronald@gmail.com
mom@kellyinvestmentgroup.com
michaeldsandiego@gmail.com
marlenamccrea@yahoo.com
m.buchanan@eversoftwater.net
m.bergthold@lcmssolutions.com
jerry92109@gmail.com
j.christiansen@contactspectrum.com
ejster@earthlink.net
cwyun1520@gmail.com
colleen@chefcityusa.com
caryl@onewebcompany.com
bmulvaney@voitco.com
bjohnsonsan@hotmail.com
tina@designperspectives.net
thall@restacct.com
sngov@pacificenterprisebank.com
emitchell@semprautilities.com
leemarshall@earthlink.net
lori@securityfencesandiego.com
josh@stingrayconstruction.com
zhashim@highlandventuregroup.com
hueyearl@yahoo.com
cwormser@sandiego.gov
gregwoodward@yahoo.com
searchn4sun@aol.com
darren@optimizepartnersllc.com
ericwohl@intellisparx.com
lwitherspoon@ntcfoundation.org
andrea@thesofiahotel.com
ken@kenwinslow.com
twilliams@quattrorealty.com
jwilliams@powerstripstudio.com
dwill@kellycapital.com
wilcoxkred@aol.com
jwhittington@stmkmgmt.com
jwhitelaw@tw2marketing.com
cwehrmaqn@pra.com
awebber@sterling-security.com
rwatson@bondhd.com
bwalsh@walshandchacon.com
sandiego@jimmychoo.com
leslie@wadecommunications.com
byronwade@cox.net
ana@taborcommunications.com
nvann@brownandbigelow.com
bvdlaw@sbcglobal.net
ion.valis@gmail.com
wurushimaconn@ccssd.org
btrotier@frea.com
danny@onewaypaint.com
michael@trimblephoto.com
jim.treadway@mtmluxurylodging.com
stoohill@luce.com
mtobin1@san.rr.com
ktilden@calamwater.com
leslie.thurman@warnerbros.com
jthomas@kellycapital.com
bryan@intellisparx.com
tom@tgc.com
dsussman@kimptongroup.com
nsurrantt@sandiego.gov
sssuper311@gmail.com
katherine@restaurantevents.com
susanmstocker@gmail.com
mstevens@mcmillin.com
salexis@san.rr.com
tstefani@calweb.com
secretsquirrelstefani@yahoo.com
kst.pierre@modernluxury.com
lunzy@bigfoot.com
asolomon@sempra.com
deeanne.snyder@visitsandiego.com
modmerchant@earthlink.net
simsbodyworks@msn.com
kens@prosystemsav.com
james.simkins@mtmluxurylodging.com
sshriver2@yahoo.com
jason.shorrock@mhusa.com
catalina@kellycapital.com
ivor@corporatehelicopters.com
gary@sandiegometro.com
nicole_sharp@hilton.com
info@ironpigalehouse.com
jonathansegal@yahoo.com
lscottdev@me.com
courtneysctt@yahoo.com
dschroeder@ucsd.edu
mark@sbptnrs.com
wallys@san.rr.com
chrissanchez@diningoutonline.com
lsanjose@chipotle.com
dsalisbury@mintz.com
erypins@sbcglobal.net
jrush@rushpress.com
tamromeo24@yahoo.com
iloan4you@aol.com
ken@caspercompany.com
briley@pd.sandiego.gov
davidridge29@hotmail.com
rhonda.lopresti@cox.net
rrauch@mail.sdsu.edu
vquinci@kellycapital.com
marc.pujalet@mtmluxurylodging.com
npioliver@msn.com
angela@cadencetravel.com
shpeagle@cox.net
mike@caspercompany.com
tpiscitello@bngconsultants.com
rpinnegar@sdcaa.com
bphilion@sourcecheck.com
scottpeters@sandiego.gov
jennifer.perkins@porternovelli.com
nicolle.penton@hilton.com
apentico@sdcaa.com
rick.patterson@alconlabs.com
jimmy@gaslamp.org
eparker@nu.edu
papers@ccdc.com
debra_palmer@hotmail.com
garner_palenske@schirmereng.com
lowens@coastal.ca.gov
roliver@edcodisposal.com
imo@adnc.com
maryconeil@msn.com
joneal@go2cpa.com
nancyoconnorlajolla@gmail.com
donovannugent@yahoo.com
cnott@ctonsite.com
amy@noelimageconsulting.com
a_nobriga@hotmail.com
mitchellperlman@gmail.com
matt.shope@cbre.com
marivi.shivers@usbank.com
kelli.silverstein@oracle.com
diego@hdhookups.com
csmith5@san.rr.com
donna.clower@sonybmg.com
sheree543@aol.com
mbarnhorst@trademarkgroup.com
sean.brosnan@american-national.com
amy@rypinslaw.com
ronald.beagle@oracle.com
dcroberts2000@yahoo.com
robert@canvasstore.com
rick@ironpigalehouse.com
richard.davidson@usbank.com
soates@sandiego.gov
bill@billneumann.com
mnelson@sdge.com
fnajjar@nyc.rr.com
jgotschalk@centurytel.net
mitchmulanix@sbcglobal.net
gmueller@tuckersadler.com
alexisamora99@gmail.com
mortensen@nautilusgeneral.com
dan@dmorrinlaw.com
donna@biasd.org
jamoradi@gmail.com
jmoradi@gmail.com
moniger.scott@sd.sysco.com
popcicle@san.rr.com
sandiego@oceanaire.com
mmiraglia@kellycapital.com
brett@moondoggies.com
fmiley@westfield.com
nmercer@sdhma.com
pmcneil@sandiego.gov
delores.mcneely@uboc.com
smcnally@sandiego.gov
jmcknight@mycingular.blackberry.net
davidm@makarproperties.com
shelby@babybirdcommunications.com
relax@spaecochateau.com
mmcdade@swmw.com
timm@barneyandbarney.com
loismathews@hotmail.com
cjmathes@yahoo.com
davemason@rebelsbrands.com
mash@nautilusgeneral.com
amartz@entropicproductions.com
celebrites@maui.net
dawn.maroney@caremore.com
mmarmon@gmail.com
michael@mmarkslaw.com
monica@moradimd.com
momallick@aol.com
bmaienschein@sandiego.gov
jmadaffer@sandiego.gov
macoskylaw@san.rr.com
steve@pranaconsulting.com
plynch@sandiego.gov
jeff.lugosi@pkfc.com
jluft@nealelectric.com
slowe@dotprinter.com
glondon@londongroup.com
elofgran@kellycapital.com
howard@howardlittman.com
info@sendmouse.com
mbllaw@earthlink.net
jle@sandag.org
ascmichaellee@gmail.com
leex4@socal.rr.com
joeltleblanc@aol.com
notladl@aol.com
landonkyle@yahoo.com
sheep_on_cliff@hotmail.com
lambstudiophoto@gmail.com
lesalakin@yahoo.com
marylacycoaching@gmail.com
genia@hpcinthecloud.com
kuritzmm@aol.com
andrew@sshintl.com
tanya.kostic@mhusa.com
jkopelman@diningout.com
gus@eliteshowservices.com
mkong@modernluxury.com
bruce@kleege.com
jimk@kellycapital.com
dkennedy@greenlawpartners.com
terri@kellyholdingsllc.com
richard@kellyholdingsllc.com
michael@kellyinvestmentgroup.com
lwkjr@delnet.com
liz@cbsanmiguel.com
leonor_v_kelly@yahoo.com
laurenashleykelly@yahoo.com
johnkelly6044@comcaast.net
tarheeljlk@aol.com
cjdevelop@gmail.com
mollieandkevin@cox.net
jewelk@cox.net
patty.danon@sdcounty.ca.gov
judson@jmisports.com
casey.jones@andaz.com
brianj@newsreview.com
ljohnston@sirote.com
steve@lasplayasprint.com
jjohnson@jgjohnson.com
bjohnsonsd@gmail.com
jeffrey.johns@am.sony.com
jinnatsr@hotmail.com
jennifergreenberg@contactems.com
pjelsma@luce.com
katejeffery@cox.net
davidjacobs@westhemgrant.com
djacobs@restacct.com
pasquale@landgrant.net
thyslop@bigfoot.com
jeff@taborcommunications.com
craig@urban-niche.com
hunt.maria@yahoo.com
benhueso@sandiego.gov
phowell@cmw.com
aleapahead@cox.net
cincinsticks@yahoo.com
chris@infdv.com
teresa@allimar.com
hobson_benito@integrits.com
patrick@artisticflorals.com
rebeccaheyl@cox.net
sue@hetzelmeade.com
ericamherrera@hotmail.com
gherreman@worldnet.att.net
salhndz@sbcglobal.net
mhendry@tsaci.com
rhemmen@dci-engineers.com
mhayley@preceptgroup.com
johnh@cloud9shuttle.com
carlee.harmonson@uboc.com
tharmon@solagehotels.com
angelina@francouomo.com
pamhamiltonlester@cox.net
dean@mrtopstyle4u.com
terrencehale@gmail.com
khale@tomshepard.com
mhagarty@luce.com
dhaga@fclaw.com
rhaerr@luce.com
kim@twentynine12.com
chrissd1@cox.net
gustafson@nautilusgeneral.com
mguerrero@paychex.com
grove4@gmail.com
ltsirrigation@gmail.com
vtabor@ccssd.org
howard@trilogymanagement.com
jeff@propmgr.us
mgraulich@mcmillin.com
dgrant@modernluxury.com
heidi.gould@fpimgt.com
carlos@pamgmt.com
pamelagold@san.rr.com
charlie@csgivens.com
lisa.gilmour@am.sony.com
brad.gietter@mhusa.com
dgibson@nu.edu
tgibbings@2020fa.com
abt715@pacbell.net
laura.genovia@fpimgt.com
brianna@taborcommunications.com
intusolu@tns.net
s_gardner@msn.com
rgantenbein@rlgventures.com
info@baronegalasso.com
alexandra.fuchsman@gmail.com
tim@thecomputeradmin.com
kevin@thecomputeradmin.com
mf@creativeintelligence.com
jena.francis@karlstrauss.com
pfons@youngsmarket.com
scott.fisk@utsandiego.com
bfish@luce.com
jfinkenberg@hotmail.com
cfidler@rchsd.org
angelica@asintur.net
kevinfaulconer@sandiego.gov
afarwell@hyatt.com
minda.enokida@am.sony.com
emma@ironpigalehouse.com
jackelliott@southernwine.com
jgelizondo@gmail.com
doug@equuscorp.com
greg@johnsonandjennings.com
cameron.durckel@gov.ca.gov
michael@starmackgroup.com
valerie@dueinc.com
ddresher@bradleyarant.com
mdrake@sirote.com
paul.downey@servingseniors.org
cambria@madremedia.com
mdossett@sandiego.gov
debbie@thedorseecompany.com
brad@prosystemsav.com
mariana_domic@yahoo.com
mdollaghan@hotmail.com
phyllis.dodds@hdsupply.com
mymediationsolution@gmail.com
jimdimatteo@san.rr.com
juliedillon@cox.net
diekman@ccdc.com
jdiebold@sandiego.gov
sdevincent@kyxy.com
gdeitsch@sirote.com
pdealy@mresorts.com
desiree@dawnoftheday.com
tddavis@sirote.com
davidsonyards@aol.com
shaneyjo@keep-a-breast.org
danziger@ccdc.com
steve.danon@mail.house.gov
pkdanon@gmail.com
noel7359@aol.com
nicole@kellycapital.com
jdadian@dadianconsulting.com
dealba00@gmail.com
mcurtis@pacbell.net
isabel@foodgirl.com
james.crocenzi@cbre.com
ingrid@croces.com
anita.h.crandall@nordstrom.com
crampton463@aol.com
chris@karlstrauss.com
craig.benedetto@att.net
scovell@qualcomm.com
ccottriall@timkenmuseum.org
cordova@ccdc.com
contreras@ccdc.com
david@cohnrestaurants.com
hcohen@destinationhotels.com
marccohan@aol.com
david.coddon@uniontrib.com
douglas@rufskin.com
tomc@roel.com
dcleary@contact-america.com
gclay@jmirealty.com
lclaiborne@pacificenterprisebank.com
mr.jrchurchill@gmail.com
carrie@johnsonandjennings.com
gs_carter@yahoo.com
ccarter@amylin.com
mcarrillo@blokhaus.com
ccarlis1@san.rr.com
fcaparso@nhcai.com
fcaminite@kellycapital.com
info@greenhaus.com
bbyrne@teledyne.com
rbush@earthlink.net
carole@gofreeform.com
steve_burton@aceparking.com
abtdick@pacbell.net
rhonda.brown@bloomingdales.com
brokow@pacbell.net
dbrody@brody-law.com
brockafellow@sandiego.gov
brewster@lifesaver1.com
bbrennan@barneyandbarney.com
boyerlaw@sbcglobal.net
ibowman@bngconsultants.com
gbowen@kellycapital.com
rbohl@bensonbohl.com
bjohnson@kellycapital.com
beth.binger@bcipr.com
sandiegocraftsman@yahoo.com
sara@pacificbeach.org
tberner@powerstripstudio.com
jo@gocommandos.com
rocio.bernal@signonsandiego.com
bberg@glumac.com
ebenson@pcsgp.com
diane.bell@uniontrib.com
tony@beechers.com
bbeckett@tsaci.com
scott@baumbergerstudio.com
allison.batstone@sdcda.org
gbarrett7@gmail.com
kristin@ideaworksadvertising.com
reelralph@aol.com
mbarnard@investwest.net
neilbane@carltongroup.com
bruce.baltin@pkfc.com
melbailey@yahoo.com
kye@mac.com
audrey@prchemistry.com
sam.attisha@cox.com
laashton@highlandventuregroup.com
sean@ideaworksadvertising.com
parnett@tsaci.com
doug@doradoenterprises.com
toniantonellis@greenbellies.com
jeremy.andrus@kimptongroup.com
simon@graphicsolutionsltd.com
andrew182@aol.com
anderson@ccdc.com
janielynn.anderson@gmail.com
gandersonsd@gmail.com
dalm@cox.net
jalleckson@profit-solutions.net
kalexen@johnsonandjennings.com
scott@hutchenspr.com
dkandsbn@roadrunner.com
caldieri@jollapo.hyatt.com
pattiaaa@grandecom.net
edwardausc@earthlink.net
tony@designperspectives.net
patm@barneyandbarney.com";

// Replace all the new lines with commas, then split (explode) by comma to get each part of the string.
$input = $lines;
$input = preg_replace("/((\r?\n)|(\r\n?))/", ',', $input);
$pieces = explode(',', $input);
foreach($pieces as $part) {
  $x = $x + 1;
}
print "$x emails <br />";

$input = $pieces;
foreach ($input as $email){
if(filter_var($email, FILTER_VALIDATE_EMAIL)) {
print "$email<br />";
$q = $q + 1;
}
else{
print "<h3>Invalid</h3>";
}
}
print "$q emails valid";

?>